name: lingo_learn
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  #  firebase
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.1.0
  firebase_core: ^2.22.0

  # localization
  easy_localization: ^3.0.2

  # DI
  get_it: ^7.6.0
  injectable: ^2.1.2

  # Modeling
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1

  # State management
  equatable: ^2.0.3
  flutter_bloc: ^8.1.2

  # dev
  dartz: ^0.10.1
  intl: ^0.18.0
  tuple: ^2.0.1
  logger: ^1.3.0

  #client
  dio: ^5.3.0

  #ui
  flutter_screenutil: ^5.7.0
  shared_preferences: ^2.1.0
  flutter_svg: ^1.1.6
  flutter_native_splash: ^2.3.0
  auto_size_text: ^3.0.0
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.2.3
  percent_indicator: ^4.2.3
  carousel_slider: ^4.2.1
  text_scroll: ^0.2.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.1.0
  form_field_validator: ^1.1.0
  fancy_shimmer_image: ^2.0.2
  dotted_border: ^2.1.0
  flutter_otp_text_field: ^1.1.1
  animated_size_and_fade:
  cupertino_tabbar:
  page_view_dot_indicator: ^2.3.0
  flutter_rating_bar: ^4.0.1
  easy_animation: ^0.0.2
  pinput: ^3.0.1
  phone_numbers_parser:
  geocoding: ^2.1.1
  geolocator: ^10.0.1
  app_settings: ^5.1.1
  readmore: ^2.2.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geocoding_platform_interface: ^2.0.1
  location_platform_interface: ^3.1.2
  map_picker: ^0.0.3
  flutter_spinkit: ^5.2.0
  map_launcher: ^2.5.0+1
  easy_stepper: ^0.8.1
  photo_view: ^0.14.0
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  bloc_test: ^9.1.1
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  share_plus: ^7.2.1
  fluttertoast: ^8.2.4
  carousel_slider: ^4.2.1

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:    - assets/image/logo.svg

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
